name: e_care_mobile
description: e-care mobile app.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.1
  http: ^0.13.3
  font_awesome_flutter: ^9.1.0
  carbon_icons: ^0.0.1
  
  


  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.4
  animated_splash_screen: ^1.1.0
  animations: ^2.0.0
  page_transition: ^2.0.1-nullsafety.0
  bouncing_widget: ^2.0.0
  flutter_bounce: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

 
  uses-material-design: true

 
  assets:
    - assets/images/



  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Thin.ttf
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Light.ttf
          style: normal

