name: e_care_mobile
description: e-care mobile app.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.1
  font_awesome_flutter: ^9.1.0
  carbon_icons: ^0.0.1+2


  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.4
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  image_picker: ^0.8.0+3
  page_transition: ^2.0.1-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

 
  uses-material-design: true

 
  assets:
    - assets/images/



  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Thin.ttf
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Light.ttf
          style: normal

